apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
spec:
  selector:
    matchLabels:
      run: udagram-reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        run: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: docker.io/cliffordusidamen/udagram-reverseproxy:v3
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-reverseproxy
