apiVersion: v1
data:
  aws_access_key_id: QUtJQTRQNFc3Mk1ZRUdQRllZRVI=
  aws_secret_access_key: MXRpOVJtLzFKZm5UcVFYZ2tubXhVM3Q1NFZGUE9TdXUvNFBhSzJlQg==
kind: Secret
metadata:
  creationTimestamp: null
  name: aws
type: string